// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvV2CmpIOGiTBDm63f_jKBMEs0gPl2ftQ',
    appId: '1:834619838181:web:f216b7829617a4b7904e0c',
    messagingSenderId: '834619838181',
    projectId: 'marketplace-app-682e4',
    authDomain: 'marketplace-app-682e4.firebaseapp.com',
    storageBucket: 'marketplace-app-682e4.firebasestorage.app',
    measurementId: 'G-G6HPW0SGF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuNj0h73zYRKLoKQWQpuMu5yTQsAz-ZnA',
    appId: '1:834619838181:android:1bf5b1356bcdc751904e0c',
    messagingSenderId: '834619838181',
    projectId: 'marketplace-app-682e4',
    storageBucket: 'marketplace-app-682e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChA1aJCTvWKWEz3VJTDS5dF-kV62NLcfM',
    appId: '1:834619838181:ios:817f0c718267ee3b904e0c',
    messagingSenderId: '834619838181',
    projectId: 'marketplace-app-682e4',
    storageBucket: 'marketplace-app-682e4.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChA1aJCTvWKWEz3VJTDS5dF-kV62NLcfM',
    appId: '1:834619838181:ios:817f0c718267ee3b904e0c',
    messagingSenderId: '834619838181',
    projectId: 'marketplace-app-682e4',
    storageBucket: 'marketplace-app-682e4.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvV2CmpIOGiTBDm63f_jKBMEs0gPl2ftQ',
    appId: '1:834619838181:web:839d93cd5ceb3f58904e0c',
    messagingSenderId: '834619838181',
    projectId: 'marketplace-app-682e4',
    authDomain: 'marketplace-app-682e4.firebaseapp.com',
    storageBucket: 'marketplace-app-682e4.firebasestorage.app',
    measurementId: 'G-TBNWWL77NJ',
  );
}
